---
name: "notify_bot"
pack: "laas"
description: "sends a notification to the registered chat bot"
enabled: true

trigger:
    type: "core.st2.generic.notifytrigger"
    parameters: {}

criteria:
    trigger.channel:
        pattern: "chatbot"
        type: "equals"

action:
    ref: "laas.send_bot_notification"
    parameters:
        message: "{{trigger.message}}"
        execution_id: "{{trigger.data.execution_id}}"
